### ISSUE TITLE
Out of sync playback while using alda.now

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda-sound-engine-clj#15]
Moved from https://github.com/alda-lang/alda-core/issues/67. (cc: @abhi18av )

See original issue for more details.

**Comment by daveyarwood** [comment]
Synopsis of where the discussion has gone so far in https://github.com/alda-lang/alda-core/issues/67:

* I have plans to revisit the "Alda in a Clojure program" workflow in Alda 2.0, which is coming at some point. At that point, your Clojure program will just be generating Alda syntax and sending it to an Alda server, as opposed to essentially _being_ the Alda server like it is now when you use the `alda.now` library.

* This boils down to writing a new Clojure library for generating Alda syntax and sending it to an Alda server.

@abhi18av It occurred to me that I'm not actually blocked on the Alda 2.0 stuff to make this change -- I could actually write the new Clojure library first, and it would be compatible with Alda 1.x servers. I like that idea because I think it would get you un-stuck, it would be a step away from relying on the bugginess of alda.now, and it would be progress toward the Alda 2.0 that I'm envisioning.

**Comment by abhi18av** [comment]
Sounds great Dave!

**Comment by daveyarwood** [comment]
Hey @abhi18av , over the past few days I made a spike of this new Clojure library I described above. I'm very happy with it so far!

https://github.com/daveyarwood/alda-clj

It has a very similar API to alda.now / alda.lisp, but instead of building and playing the score itself, it shells out to `alda` and uses the server you have running.

Try it out and let me know what you think!

I'm considering quietly removing Alda documentation about inline Clojure code and alda.now, and instead including some information in the docs about using external tools like alda-clj to create scores programmatically.

**Comment by daveyarwood** [comment]
P.S. I have a TODO list item to improve the documentation for alda-clj. Hopefully it's clear enough from what's in the README and examples how to get started! Feel free to ping me here or in [slack](https://slack.alda.io) if you need any help.

**Comment by abhi18av** [comment]
Hi @daveyarwood ,

Thank you for making progress in this direction!  Yes, the README is wonderfully descriptive. I am already trying to make some coherent reference for both alda notations here in https://github.com/abhi18av/alda-musician 

I've since explored the`alda-now` library since last night and I've a few general suggestions and a couple questions which I'd put forward now as separate issues in the https://github.com/daveyarwood/alda-clj repo :)

I'll close this issue as this is now effectively resolved 👍

**Comment by abhi18av** [comment]
Also, I'd like to highlight that `alda` is effectively liberated from the `clojure` world after this move to shelling-out to the `alda cli`.

I'm looking forward to writing a couple clients in different languages and since it's almost reduced to a text generation problem we could wrap libraries like `euterpea` http://www.euterpea.com/ from the Haskell world etc.

**Comment by daveyarwood** [comment]
@abhi18av Awesome, I'm happy that you're digging into this!

Liberating Alda from the Clojure world is exactly what I had in mind. In the README for alda-clj, I outlined some reasons that implementing Alda in Clojure is less than ideal, and the plan for Alda 2.0 is to reimplement the whole thing from the ground up on a different runtime. It will take a lot of work, but at least we have Alda 1.x as a prototype that we can use for reference.

I'd love to see client libraries written in other languages like Haskell (integration with Euterpea would be really cool!). It really is just a matter of generating a string of Alda code and sending it to the `alda` client!

**Comment by abhi18av** [comment]
😄  I'm always amazed at your enthusiasm for this @daveyarwood
