### ISSUE TITLE
Midi export missing instruments

### ISSUE THREAD

**Issue by 0atman** [alda-lang/alda-sound-engine-clj#16]
I have a simple score:

```python
bassline = piano: [o1 c16 > c > c > c] * 4
drums = midi-percussion: o2 [c4 c c c]

bassline * 2
drums * 2
```

Which plays very nicely with alda. However, on midi export, I'm experiencing dropped instruments.

Oddly, in an inconsistent way depending on what program plays the midi file:

**Timidity seems to only recognize the drums:**
```
alda export -f UL1.alda -o ul1.mid && timidity ul1.mid
[27713] Parsing/evaluating...
[27713] Done.
Requested buffer size 32768, fragment size 8192
ALSA pcm 'default' set buffer size 32768, period size 8192 bytes
Playing ul1.mid
MIDI file: ul1.mid
Format: 0  Tracks: 1  Divisions: 128
No instrument mapped to tone bank 0, program 81 - this instrument will not be heard
No pre-resampling cache hit
Playing time: ~7 seconds
Notes cut: 0
Notes lost totally: 0
```

**Whereas my DAW, Bitwig, only recognizes the piano:**

![Screenshot from 2019-04-15 15-42-43](https://user-images.githubusercontent.com/114097/56141652-21012600-5f95-11e9-9a78-165da3c97d8c.png)

The drums I can live without, for my personal workflow. So it's still MASSIVELY useful to me to have this new midi export - thank you! But, I wonder what's happening here?

**Comment by 0atman** [comment]
I've tried `midi-saw-wave` as well as `piano`, both aren't heard in timidity, both show up in Bitwig.

**Comment by daveyarwood** [comment]
Interesting! I knew there would be some edge cases. Please continue to file issues as you find them. I'll dig in when I find the time, unless someone else beats me to the punch :)

**Comment by 0atman** [comment]
No doubt I'll find 'em all - I've been waiting for this moment to write a whole album of music entirely with Alda!
Watch this space... https://twitter.com/namtaomusic/status/1117787281623064576

**Comment by TBuc** [comment]
@0atman reading some topics in Bitwig's forum I could notice there are a few bugs with handling multiple instruments that don't seem to be related to this specific case, but who knows. Did you try contacting their support for this specific issue? Seems they gave some very useful insights to other users in the past (also making them aware of known bugs). That might help, one way or another!

**Comment by TBuc** [comment]
@0atman I've also noticed that, when exporting your score then importing it to Notation Player 3, both `piano` and `midi-percussion` get mapped to `Acoustic Gran Piano`. Maybe this means nothing to Bitwig, but don't wanna hit a edge case.

As an additional test, could you try replacing `midi-percussion` with `violin` in your score, then try exporting it to midi then importing it to Bitwig and see what happens?

**Comment by daveyarwood** [comment]
I think the behavior must vary from system to system. On my laptop, when I export the score above and play it in timidity, I see slightly different output:

```
$ timidity --verbose /tmp/oatman.mid 
Requested buffer size 32768, fragment size 8192
ALSA pcm 'default' set buffer size 32768, period size 8192 bytes
Playing /tmp/oatman.mid
MIDI file: /tmp/oatman.mid
Format: 0  Tracks: 1  Divisions: 128
171 supported events, 175710 samples, time 0:03
Tonebank 0 0: Tone_000/000_Acoustic_Grand_Piano.pat
Drumset 0 36(C): Drum_000/036_Kick_2.pat
Resample cache: Key 4/4(100.0%) Sample 150.7K/150.7K(100.0%)
Playing time: ~7 seconds
Notes cut: 0
Notes lost totally: 0
```

Differences that I notice:

* Whereas @0atman 's timidity output included the message `No instrument mapped to tone bank 0, program 81 - this instrument will not be heard`, mine does not.
* `--verbose` output makes it look like timidity did recognize that there is a piano and a kick drum.
* I hear both the piano and the drums. (I did have to adjust the score to lower the piano volume in order to hear the bass drum. At first, I thought I was only hearing the piano.)

I was curious if this was a timidity issue, so I imported the MIDI file into MuseScore and it looks and sounds right. Here is a screenshot:

![2019-04-16-202134_766x205_scrot](https://user-images.githubusercontent.com/4909079/56252576-681b1400-6086-11e9-84a1-1cec4e94bdae.png)

One thing I'm kind of curious about is the fact that we're only creating 1 MIDI track. I'm still a little bit confused about the difference between a Track and a Channel in Java MIDI terminology.

ref: https://docs.oracle.com/javase/7/docs/api/javax/sound/midi/Track.html

I _think_ we're doing the correct thing by having a single track with multiple channels, but I'm not 100% sure about that. At the very least, it might be worth trying to use a separate track for each channel and see if that helps compatibility with timidity, Bitwig, and other programs.

**Comment by daveyarwood** [comment]
@0atman [I just played around with the MIDI export code for a little bit](https://github.com/alda-lang/alda-sound-engine-clj/commit/e0f2590ee5d1485fc03bb7b3ed8ff1f7693e501e) and I was able to tweak it so that each channel is on its own track, and accordingly, we're exporting a Type 1 (multiple tracks) MIDI file instead of a Type 0 (one track w/ multiple channels) MIDI file.

I uploaded a build of `alda` to keybase -- try it out and let me know if it works any better for you:

```
curl https://daveyarwood.keybase.pub/alda/builds/alda-2019-04-16-1tpc > /tmp/alda
chmod +x /tmp/alda
/tmp/alda downup
```

Then try exporting your score again and see if it makes any difference. One thing you should notice, when using timidity, is that it says it's MIDI Type 1 ("Format: 1") and that there is more than 1 track. (Interestingly, it seems to add an extra track, so if your score has 2 instrument parts, it will say there are 3 tracks. I'm not sure what that's all about.

```
# excerpt of timidity output when playing a score I exported using this alda build
Format: 1  Tracks: 3  Divisions: 128
```

On my machine, besides the fact that timidity indicates there are multiple tracks and the MIDI file is Type 1, I don't notice any difference in sound and the import experience in MuseScore is roughly the same. I'd be curious to hear how things go on your end.

**Comment by 0atman** [comment]
This now works perfectly on the latest Alda (with) timidity. <3
I have no idea what version I was on when I posted this - my server says 1.3.1 now!

It even imports perfectly into Bitwig now (though I'm on a higher version of bitwig, so all bets are off who fixed this):
![Screenshot from 2019-06-22 15-45-27](https://user-images.githubusercontent.com/114097/59965361-cd670780-9504-11e9-96c0-3ce1ee8ea7ff.png)

**Comment by daveyarwood** [comment]
Great, I'm glad it's working now!

Nothing has changed on the Alda side with respect to MIDI export, so I guess it may have been an issue that was fixed in Bitwig?

**Comment by 0atman** [comment]
That's fascinating. I'll try it on a machine with the older version of
bitwig to confirm.

(I tried alda-mode today and fell in love all over again!)

**Comment by daveyarwood** [comment]
@0atman I'm going to close this issue since it's been a while and it sounds like the issue was fixed. Feel free to re-open if you're still running into problems!

**Comment by 0atman** [comment]
Cheers Dave!
